# roles/node/defaults/main.yml
---
node_package_managers:
  - name: pnpm
    version: latest
  - name: yarn
    version: latest

node_packages:
  - globals
  - eslint
  - prettier
  - typescript
  - typescript-eslint
  - eslint-config-prettier
  - "@eslint/js"
  - "@prettier/plugin-xml"

node_packages_abandoned: []

node_pnpm_home: "{{ ansible_facts['env']['HOME'] }}/Library/pnpm"
