$ANSIBLE_VAULT;1.1;AES256
30613634323666363531306132633932303032666634396466646532373436633439623734366430
3862643033363932306564616462323764303164633231390a353264313838656366393565363237
62623461386233313163663664306133366165303833616537363936393363326534363635646264
6337646633323432370a663637336565643261643032656163633637613539373063393037376333
36666531643833323562373930326235336430646230313830313462333261653664626263633030
36643536633635623665643866666665663235333466353432663730653138396233343062333864
65363336343834383666396265666535353635623830313734653636313931646437386131343138
36393736663361653639656233666366303738626264626631376533633062343937343561633365
65333062666635623065333162386330373539316462373063663238326363346638646432383066
31336633613036396236303139636234333937653430656331636565303764646164336665633535
61363034633966643462336562623662306362333266613539643036356464616266306437336630
63346536656330333163326435336334313734333930373035353064653664666135326165386334
3961
