# host_vars/jlm2/ssh_vars.yml
---
ssh_host_default_identities:
  - "{{ ssh_key_lojoja_ed25519 }}"
  - "{{ ssh_key_lojoja_rsa }}"

ssh_host_github_alt_identities:
  - "{{ ssh_key_snldev_remote }}"

ssh_keys:
  - "{{ ssh_key_lojoja_ed25519 }}"
  - "{{ ssh_key_lojoja_rsa }}"
  - "{{ ssh_key_snldev_remote }}"
ssh_keys_remove: []
